/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-06-04 07:43:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class carousel_002dbox_002dnewguide_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 가이드구함 새 글을 보여주는 부분 -->\r\n");
      out.write("<div class=\"full-width-box bottom-padding cm-padding-bottom-36\">\r\n");
      out.write("\t  <div class=\"fwb-bg fwb-fixed band-5\"><div class=\"overlay\"></div></div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div class=\"container\">\r\n");
      out.write("\t\t<div class=\"title-box title-white\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"btn\">More <span class=\"glyphicon glyphicon-arrow-right\"></span></a>\r\n");
      out.write("\t\t\t<h1 class=\"title no-top-padding\">여행자가 필요해~~(가이드가 여행자를 모집하기 위해 글을 올리는 곳)</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row text-center\">\r\n");
      out.write("\t\t  <div class=\"col-sm-3 col-md-3 rotation employee\">\r\n");
      out.write("\t\t\t<div class=\"default\">\r\n");
      out.write("\t\t\t  <div class=\"image\">\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/team-1.jpg\" alt=\"\" title=\"\" width=\"270\" height=\"270\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<div class=\"vertical\">\r\n");
      out.write("\t\t\t\t  <h3 class=\"name\">가이드가 올린 글 제목</h3>\r\n");
      out.write("\t\t\t\t  <div class=\"role\">가이드 이름</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"employee-hover\">\r\n");
      out.write("\t\t\t  <h3 class=\"name\">가이드 이름</h3>\r\n");
      out.write("\t\t\t  <div class=\"role\">지역</div>\r\n");
      out.write("\t\t\t  <div class=\"image\">\r\n");
      out.write("\t\t\t  \t<!-- 가이드 프로필 사진을 넣어주자 -->\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/team-1.jpg\" alt=\"\" title=\"\" width=\"270\" height=\"270\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div>\r\n");
      out.write("\t\t\t\t<p>하고자 하는 여행에 대한 간단한 설명</p>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>사용언어: </b>한국어, 영어</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>관심사: </b>맛집, 야경</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>가격: </b>$10 / a hour</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div><!-- .employee-hover -->\r\n");
      out.write("\t\t  </div><!-- .employee \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  --><div class=\"col-sm-3 col-md-3 rotation employee\">\r\n");
      out.write("\t\t\t<div class=\"default\">\r\n");
      out.write("\t\t\t  <div class=\"image\">\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/team-1.jpg\" alt=\"\" title=\"\" width=\"270\" height=\"270\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<div class=\"vertical\">\r\n");
      out.write("\t\t\t\t  <h3 class=\"name\">가이드가 올린 글 제목</h3>\r\n");
      out.write("\t\t\t\t  <div class=\"role\">가이드 이름</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"employee-hover\">\r\n");
      out.write("\t\t\t  <h3 class=\"name\">가이드 이름</h3>\r\n");
      out.write("\t\t\t  <div class=\"role\">지역</div>\r\n");
      out.write("\t\t\t  <div class=\"image\">\r\n");
      out.write("\t\t\t  \t<!-- 가이드 프로필 사진을 넣어주자 -->\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/team-1.jpg\" alt=\"\" title=\"\" width=\"270\" height=\"270\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div>\r\n");
      out.write("\t\t\t\t<p>하고자 하는 여행에 대한 간단한 설명</p>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>사용언어: </b>한국어, 영어</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>관심사: </b>맛집, 야경</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>가격: </b>$10 / a hour</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div><!-- .employee-hover -->\r\n");
      out.write("\t\t  </div><!-- .employee\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  --><div class=\"col-sm-3 col-md-3 rotation employee\">\r\n");
      out.write("\t\t\t<div class=\"default\">\r\n");
      out.write("\t\t\t  <div class=\"image\">\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/team-1.jpg\" alt=\"\" title=\"\" width=\"270\" height=\"270\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<div class=\"vertical\">\r\n");
      out.write("\t\t\t\t  <h3 class=\"name\">가이드가 올린 글 제목</h3>\r\n");
      out.write("\t\t\t\t  <div class=\"role\">가이드 이름</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"employee-hover\">\r\n");
      out.write("\t\t\t  <h3 class=\"name\">가이드 이름</h3>\r\n");
      out.write("\t\t\t  <div class=\"role\">지역</div>\r\n");
      out.write("\t\t\t  <div class=\"image\">\r\n");
      out.write("\t\t\t  \t<!-- 가이드 프로필 사진을 넣어주자 -->\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/team-1.jpg\" alt=\"\" title=\"\" width=\"270\" height=\"270\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div>\r\n");
      out.write("\t\t\t\t<p>하고자 하는 여행에 대한 간단한 설명</p>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>사용언어: </b>한국어, 영어</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>관심사: </b>맛집, 야경</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>가격: </b>$10 / a hour</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div><!-- .employee-hover -->\r\n");
      out.write("\t\t  </div><!-- .employee\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  --><div class=\"col-sm-3 col-md-3 rotation employee\">\r\n");
      out.write("\t\t\t<div class=\"default\">\r\n");
      out.write("\t\t\t  <div class=\"image\">\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/team-1.jpg\" alt=\"\" title=\"\" width=\"270\" height=\"270\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<div class=\"vertical\">\r\n");
      out.write("\t\t\t\t  <h3 class=\"name\">가이드가 올린 글 제목</h3>\r\n");
      out.write("\t\t\t\t  <div class=\"role\">가이드 이름</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"employee-hover\">\r\n");
      out.write("\t\t\t  <h3 class=\"name\">가이드 이름</h3>\r\n");
      out.write("\t\t\t  <div class=\"role\">지역</div>\r\n");
      out.write("\t\t\t  <div class=\"image\">\r\n");
      out.write("\t\t\t  \t<!-- 가이드 프로필 사진을 넣어주자 -->\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/team-1.jpg\" alt=\"\" title=\"\" width=\"270\" height=\"270\">\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div>\r\n");
      out.write("\t\t\t\t<p>하고자 하는 여행에 대한 간단한 설명</p>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>사용언어: </b>한국어, 영어</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>관심사: </b>맛집, 야경</div>\r\n");
      out.write("\t\t\t\t<div class=\"contact\"><b>가격: </b>$10 / a hour</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div><!-- .employee-hover -->\r\n");
      out.write("\t\t  </div><!-- .employee -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div><!-- .full-width-box -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
