/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-06-04 07:43:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("  <div class=\"footer-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row sidebar\">\r\n");
      out.write("\t\t<aside class=\"col-xs-12 col-sm-6 col-md-3 widget social\">\r\n");
      out.write("\t\t  <div class=\"title-block\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">Follow Us</h3>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <p>Follow us in social media</p>\r\n");
      out.write("\t\t  <div class=\"social-list\">\r\n");
      out.write("\t\t\t<a class=\"icon rounded icon-facebook\" href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("\t\t\t<a class=\"icon rounded icon-twitter\" href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("\t\t\t<a class=\"icon rounded icon-google\" href=\"#\"><i class=\"fa fa-google\"></i></a>\r\n");
      out.write("\t\t\t<a class=\"icon rounded icon-linkedin\" href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"clearfix\"></div>\r\n");
      out.write("        </aside>\r\n");
      out.write("\r\n");
      out.write("\t\t<aside class=\"col-xs-12 col-sm-6 col-md-3 widget newsletter\">\r\n");
      out.write("\t\t  <div class=\"title-block\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">Newsletter Signup</h3>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div>\r\n");
      out.write("\t\t\t<p>Sign up for newsletter</p>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t<form class=\"subscribe-form\" method=\"post\" action=\"php/subscribe.php\">\r\n");
      out.write("\t\t\t  <input class=\"form-control email\" type=\"email\" name=\"subscribe\">\r\n");
      out.write("\t\t\t  <button class=\"submit\">\r\n");
      out.write("\t\t\t\t<span class=\"glyphicon glyphicon-arrow-right\"></span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("\t\t\t  <span class=\"form-message\" style=\"display: none;\"></span>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</aside><!-- .newsletter -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<aside class=\"col-xs-12 col-sm-6 col-md-3 widget links\">\r\n");
      out.write("\t\t  <div class=\"title-block\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">Information</h3>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <nav>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t  <li><a href=\"#\">About us</a></li>\r\n");
      out.write("\t\t\t  <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("\t\t\t  <li><a href=\"#\">Terms &amp; Condotions</a></li>\r\n");
      out.write("\t\t\t  <li><a href=\"#\">Secure payment</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t  </nav>\r\n");
      out.write("        </aside>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<aside class=\"col-xs-12 col-sm-6 col-md-3 widget links\">\r\n");
      out.write("\t\t  <div class=\"title-block\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">My account</h3>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <nav>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t  <li><a href=\"#\">My account</a></li>\r\n");
      out.write("\t\t\t  <li><a href=\"#\">Order History</a></li>\r\n");
      out.write("\t\t\t  <li><a href=\"#\">Wish List</a></li>\r\n");
      out.write("\t\t\t  <li><a href=\"#\">Newsletter</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t  </nav>\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </div><!-- .footer-top -->\r\n");
      out.write("\t\r\n");
      out.write("  <div class=\"footer-bottom\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"copyright col-xs-12 col-sm-3 col-md-3\">\r\n");
      out.write("\t\t  Copyright © ItemBridge Inc., 2013\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"phone col-xs-6 col-sm-3 col-md-3\">\r\n");
      out.write("          <div class=\"footer-icon\">\r\n");
      out.write("\t\t\t<svg x=\"0\" y=\"0\" width=\"16px\" height=\"16px\" viewBox=\"0 0 16 16\" enable-background=\"new 0 0 16 16\" xml:space=\"preserve\">\r\n");
      out.write("\t\t\t  <path fill=\"#c6c6c6\" d=\"M11.001,0H5C3.896,0,3,0.896,3,2c0,0.273,0,11.727,0,12c0,1.104,0.896,2,2,2h6c1.104,0,2-0.896,2-2\r\n");
      out.write("\t\t\t  c0-0.273,0-11.727,0-12C13.001,0.896,12.105,0,11.001,0z M8,15c-0.552,0-1-0.447-1-1s0.448-1,1-1s1,0.447,1,1S8.553,15,8,15z\r\n");
      out.write("\t\t\t  M11.001,12H5V2h6V12z\"></path>\r\n");
      out.write("\t\t\t</svg>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          <strong class=\"title\">Call Us:</strong> +1 (877) 123-45-67 <br>\r\n");
      out.write("          <strong>or</strong> +1 (777) 123-45-67\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"address col-xs-6 col-sm-3 col-md-3\">\r\n");
      out.write("          <div class=\"footer-icon\">\r\n");
      out.write("\t\t\t<svg x=\"0\" y=\"0\" width=\"16px\" height=\"16px\" viewBox=\"0 0 16 16\" enable-background=\"new 0 0 16 16\" xml:space=\"preserve\">\r\n");
      out.write("\t\t\t  <g>\r\n");
      out.write("\t\t\t\t<g>\r\n");
      out.write("\t\t\t\t  <path fill=\"#c6c6c6\" d=\"M8,16c-0.256,0-0.512-0.098-0.707-0.293C7.077,15.491,2,10.364,2,6c0-3.309,2.691-6,6-6\r\n");
      out.write("\t\t\t\t  c3.309,0,6,2.691,6,6c0,4.364-5.077,9.491-5.293,9.707C8.512,15.902,8.256,16,8,16z M8,2C5.795,2,4,3.794,4,6\r\n");
      out.write("\t\t\t\t  c0,2.496,2.459,5.799,4,7.536c1.541-1.737,4-5.04,4-7.536C12.001,3.794,10.206,2,8,2z\"></path>\r\n");
      out.write("\t\t\t\t</g>\r\n");
      out.write("\t\t\t\t<g>\r\n");
      out.write("\t\t\t\t  <circle fill=\"#c6c6c6\" cx=\"8.001\" cy=\"6\" r=\"2\"></circle>\r\n");
      out.write("\t\t\t\t</g>\r\n");
      out.write("\t\t\t  </g>\r\n");
      out.write("\t\t\t</svg>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          49 Archdale, 2B Charleston 5655, Excel Tower<br> OPG Rpad, 4538FH\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"col-xs-12 col-sm-3 col-md-3\">\r\n");
      out.write("          <a href=\"#\" class=\"up\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-arrow-up\"></span>\r\n");
      out.write("\t\t  </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div><!-- .footer-bottom -->\r\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
