/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-06-04 07:43:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class travel_002dreview_002dinformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t  <div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-sm-12 col-md-6 promo-partners bottom-padding\">\r\n");
      out.write("\t\t  <div class=\"title-box\">\r\n");
      out.write("\t\t  \t<a href=\"#\" class=\"btn\">More <span class=\"glyphicon glyphicon-arrow-right\"></span></a>\r\n");
      out.write("\t\t\t<h2 class=\"title\">Travel Information</h2>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"row manufactures manufactures-list\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 여행정보 대표로 3개만 나오게 하는부분. 서울 경기 부산 정도만 넣으면 어떨지? -->\r\n");
      out.write("\t\t\t<div class=\"make-wrapper\">\r\n");
      out.write("\t\t\t  <a href=\"#\" class=\"make\">\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/make-2.png\" width=\"128\" height=\"128\" alt=\"\">\r\n");
      out.write("\t\t\t  </a>\r\n");
      out.write("\t\t\t</div><!--\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t--><div class=\"make-wrapper\">\r\n");
      out.write("\t\t\t  <a href=\"#\" class=\"make\">\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/make-3.png\" width=\"128\" height=\"128\" alt=\"\">\r\n");
      out.write("\t\t\t  </a>\r\n");
      out.write("\t\t\t</div><!--\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t--><div class=\"make-wrapper\">\r\n");
      out.write("\t\t\t  <a href=\"#\" class=\"make\">\r\n");
      out.write("\t\t\t\t<img class=\"replace-2x\" src=\"content/img/make-4.png\" width=\"128\" height=\"128\" alt=\"\">\r\n");
      out.write("\t\t\t  </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <p> 여행정보입니당~~~ </p>\r\n");
      out.write("\t\t  <p> 자세한 정보는 위에 더보기를 눌러라~~~ </p>\r\n");
      out.write("\t\t</div><!-- .promo-partners -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-sm-12 col-md-6\">\r\n");
      out.write("\t\t  <div class=\"title-box\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"btn\">More <span class=\"glyphicon glyphicon-arrow-right\"></span></a>\r\n");
      out.write("\t\t\t<h2 class=\"title\">Latest Posts</h2>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <ul class=\"latest-posts\">\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t  <a href=\"#\"><img class=\"image img-circle replace-2x\" src=\"content/img/product-1-84.jpg\" alt=\"\" title=\"\" width=\"84\" height=\"84\" data-appear-animation=\"rotateIn\"></a>\r\n");
      out.write("\t\t\t  <div class=\"meta\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><span class=\"daekyu\">인기 여행기 글 제목 abcdefg...1</span></a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t  인기 여행기 글 내용 일부......1\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t  <a href=\"#\"><img class=\"image img-circle replace-2x\" src=\"content/img/product-1-84.jpg\" alt=\"\" title=\"\" width=\"84\" height=\"84\" data-appear-animation=\"rotateIn\"></a>\r\n");
      out.write("\t\t\t  <div class=\"meta\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><span class=\"daekyu\">인기 여행기 글 제목 abcdefg...2</span></a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t  인기 여행기 글 내용 일부......2\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t  <a href=\"#\"><img class=\"image img-circle replace-2x\" src=\"content/img/product-1-84.jpg\" alt=\"\" title=\"\" width=\"84\" height=\"84\" data-appear-animation=\"rotateIn\"></a>\r\n");
      out.write("\t\t\t  <div class=\"meta\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><span class=\"daekyu\">인기 여행기 글 제목 abcdefg...3</span></a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t  인기 여행기 글 내용 일부......3\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
