/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-06-04 08:12:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.travel_005finfo.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class travel_005finfo_005felement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"breadcrumb-box\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("<section id=\"main\">\r\n");
      out.write("  <header class=\"page-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h1 class=\"title\">여행정보</h1>\r\n");
      out.write("    </div>\t\r\n");
      out.write("  </header>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <article class=\"content\">\r\n");
      out.write("\t  <div class=\"content portfolio portfolio4 col-sm-12 col-md-12\">\r\n");
      out.write("\t  <div class=\"map-box bottom-padding\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t  class=\"map-canvas\"\r\n");
      out.write("\t\t  data-zoom=\"7\"\r\n");
      out.write("\t\t  data-lat=\"35.748441\"\r\n");
      out.write("\t\t  data-lng=\"127.985664\"\r\n");
      out.write("\t\t  data-title=\"Bryant Park\"\r\n");
      out.write("\t\t  data-content=\"New York, NY\"\r\n");
      out.write("\t\t   style=\"height:700px;\"></div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"title-box\"><h3 class=\"title slim\">관련 글</h3></div>\r\n");
      out.write("\t  <div class=\"product-tab\">\r\n");
      out.write("\t\t  <ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"#description\">여행정보</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#reviews\">여행후기</a></li>\r\n");
      out.write("\t\t  </ul><!-- .nav-tabs -->\t\r\n");
      out.write("\t\t  <div class=\"tab-content\">\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\t<div class=\"tab-pane active\" id=\"description\">\r\n");
      out.write("\t  \r\n");
      out.write("\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t  \t<thead>\r\n");
      out.write("\t\t  \t\t<tr>\r\n");
      out.write("\t\t  \t\t\t<th colspan=\"6\" class=\"\">ㅇㅇ 지역의 정보를 확인하세여</th>\r\n");
      out.write("\t\t  \t\t</tr>\r\n");
      out.write("\t\t  \t</thead>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  \t<tbody>\r\n");
      out.write("\t\t  \t\t<tr>\r\n");
      out.write("\t\t  \t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t  \t\t\t<div data-appear-animation=\"bounceInLeft\">\r\n");
      out.write("\t\t  \t\t\t\t<div class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"livicon\" data-n=\"phone\" data-s=\"42\" data-c=\"000\" data-hc=\"0\"></div>\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t  \t\t</td>\r\n");
      out.write("\t\t  \t\t\t<td>지역번호</td>\r\n");
      out.write("\t\t  \t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t  \t\t\t<div data-appear-animation=\"bounceInUp\">\r\n");
      out.write("\t\t  \t\t\t\t<div class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"livicon\" data-n=\"money\" data-s=\"42\" data-c=\"000\" data-hc=\"0\"></div>\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t  \t\t</td>\r\n");
      out.write("\t\t  \t\t\t<td>버스요금</td>\r\n");
      out.write("\t\t  \t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t  \t\t\t<div data-appear-animation=\"bounceInRight\">\r\n");
      out.write("\t\t  \t\t\t\t<div class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"livicon\" data-n=\"car\" data-s=\"42\" data-c=\"000\" data-hc=\"0\"></div>\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t  \t\t</td>\r\n");
      out.write("\t\t  \t\t\t<td>택시요금</td>\r\n");
      out.write("\t\t  \t\t</tr>\r\n");
      out.write("\t\t  \t\t<tr>\r\n");
      out.write("\t\t  \t\t\t<td>111</td>\r\n");
      out.write("\t\t  \t\t\t<td>111</td>\r\n");
      out.write("\t\t  \t\t\t<td>111</td>\r\n");
      out.write("\t\t  \t\t</tr>\r\n");
      out.write("\t\t  \t\t<tr>\r\n");
      out.write("\t\t  \t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t  \t\t\t<div data-appear-animation=\"bounceInLeft\">\r\n");
      out.write("\t\t  \t\t\t\t<div class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"livicon\" data-n=\"pacman\" data-s=\"42\" data-c=\"000\" data-hc=\"0\"></div>\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t  \t\t</td>\r\n");
      out.write("\t\t  \t\t\t<td>유명한 먹거리</td>\r\n");
      out.write("\t\t  \t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t  \t\t\t<div data-appear-animation=\"bounceInDown\">\r\n");
      out.write("\t\t  \t\t\t\t<div class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"livicon\" data-n=\"home\" data-s=\"42\" data-c=\"000\" data-hc=\"0\"></div>\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t  \t\t</td>\r\n");
      out.write("\t\t  \t\t\t<td>유명 장소</td>\r\n");
      out.write("\t\t  \t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t  \t\t\t<div data-appear-animation=\"bounceInRight\">\r\n");
      out.write("\t\t  \t\t\t\t<div class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"livicon\" data-n=\"plane-up\" data-s=\"42\" data-c=\"000\" data-hc=\"0\"></div>\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t  \t\t</td>\r\n");
      out.write("\t\t  \t\t\t<td>가까운 공항</td>\r\n");
      out.write("\t\t  \t\t</tr>\r\n");
      out.write("\t\t  \t\t<tr>\r\n");
      out.write("\t\t  \t\t\t<td>111</td>\r\n");
      out.write("\t\t  \t\t\t<td>111</td>\r\n");
      out.write("\t\t  \t\t\t<td>111</td>\r\n");
      out.write("\t\t  \t\t</tr>\r\n");
      out.write("\t\t  \t</tbody>\r\n");
      out.write("\t\t  </table>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"tab-pane\" id=\"reviews\">\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t  <div class=\"title-box\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"btn\">More <span class=\"glyphicon glyphicon-arrow-right\"></span></a>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <ul class=\"latest-posts\">\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t  <a href=\"#\"><img class=\"image img-circle replace-2x\" src=\"content/img/product-1-84.jpg\" alt=\"\" title=\"\" width=\"84\" height=\"84\" data-appear-animation=\"rotateIn\"></a>\r\n");
      out.write("\t\t\t  <div class=\"meta\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><span class=\"daekyu\">인기 여행기 글 제목 abcdefg...1</span></a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t  인기 여행기 글 내용 일부......1\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t  <a href=\"#\"><img class=\"image img-circle replace-2x\" src=\"content/img/product-1-84.jpg\" alt=\"\" title=\"\" width=\"84\" height=\"84\" data-appear-animation=\"rotateIn\"></a>\r\n");
      out.write("\t\t\t  <div class=\"meta\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><span class=\"daekyu\">인기 여행기 글 제목 abcdefg...2</span></a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t  인기 여행기 글 내용 일부......2\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t  <a href=\"#\"><img class=\"image img-circle replace-2x\" src=\"content/img/product-1-84.jpg\" alt=\"\" title=\"\" width=\"84\" height=\"84\" data-appear-animation=\"rotateIn\"></a>\r\n");
      out.write("\t\t\t  <div class=\"meta\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><span class=\"daekyu\">인기 여행기 글 제목 abcdefg...3</span></a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"description\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t  인기 여행기 글 내용 일부......3\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  </div><!-- .tab-content -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</article><!-- .content -->\r\n");
      out.write("  </div>\r\n");
      out.write("</section><!-- #main -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
