/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-06-04 08:07:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"HTML5 Template\">\r\n");
      out.write("\t\t<meta name=\"description\" content=\"Progressive — Responsive Multipurpose HTML Template\">\r\n");
      out.write("\t\t<meta name=\"author\" content=\"itembridge.com\">\r\n");
      out.write("\t\t<meta class=\"viewport\" name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Favicon -->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"./resources/img/favicon.ico\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Font -->\r\n");
      out.write("\t\t<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Arimo:400,700,400italic,700italic'>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Plugins CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/bootstrap.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/font-awesome.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/jslider.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/revslider/settings.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/jquery.fancybox.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/animate.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/video-js.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/morris.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/royalslider/royalslider.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/royalslider/skins/minimal-white/rs-minimal-white.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/layerslider/css/layerslider.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/ladda.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/datepicker.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/jquery.scrollbar.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Theme CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/style.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Custom CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/customizer/pages.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"./resources/css/customizer/home-pages-customizer.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- IE Styles-->\r\n");
      out.write("\t\t<!-- <link rel='stylesheet' href=\"../css/ie/ie.css\"> -->\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Body 시작 -->\r\n");
      out.write("\t<body class=\"fixed-header hidden-top\">\r\n");
      out.write("\t\t<div class=\"page-box\">\r\n");
      out.write("\t\t\t<div class=\"page-box-content\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 로그인/회원가입 들어갈 수 있는 버튼 나와있는 부분 -->\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/top-box.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 상단 메뉴 -->\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 슬라이드형식 사진 -->\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/rs-slider.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 추천 여행정보 -->\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/travel-review-information.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<section id=\"main\">\r\n");
      out.write("\t\t\t\t\t<article class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/carousel-box-recommended-guide.jsp", out, false);
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/carousel-box-newguide.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/carousel-box-newtraveler.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t</section><!-- #main -->\r\n");
      out.write("\t\t\t</div><!-- .page-box-content -->\r\n");
      out.write("\t\t</div><!-- .page-box -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 각종 Javascript -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--[if (!IE)|(gt IE 8)]><!-->\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery-2.1.3.min.js\"></script>\r\n");
      out.write("\t\t<!--<![endif]-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--[if lte IE 8]>\r\n");
      out.write("\t\t<script src=\"js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\t<script src=\"./resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/price-regulator/jshashtable-2.1_src.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/price-regulator/jquery.numberformatter-1.2.3.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/price-regulator/tmpl.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/price-regulator/jquery.dependClass-0.1.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/price-regulator/draggable-0.1.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/price-regulator/jquery.slider.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.carouFredSel-6.2.1-packed.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.touchwipe.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.elevateZoom-3.0.8.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.imagesloaded.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.appear.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.fancybox.pack.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.knob.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.selectBox.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.royalslider.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.tubular.1.0.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/SmoothScroll.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/country.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/spin.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/ladda.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/masonry.pkgd.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/morris.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/raphael.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/video.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/pixastic.custom.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/livicons-1.4.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/layerslider/greensock.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/layerslider/layerslider.transitions.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/layerslider/layerslider.kreaturamedia.jquery.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/jquery.themepunch.tools.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/jquery.themepunch.revolution.min.js\"></script>\r\n");
      out.write("\t\t<!-- SLIDER REVOLUTION 5.0 EXTENSIONS  \r\n");
      out.write("\t\t(Load Extensions only on Local File Systems !\r\n");
      out.write("\t\tThe following part can be removed on Server for On Demand Loading) -->\t\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/extensions/revolution.extension.actions.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/extensions/revolution.extension.carousel.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/extensions/revolution.extension.kenburn.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/extensions/revolution.extension.layeranimation.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/extensions/revolution.extension.migration.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/extensions/revolution.extension.navigation.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/extensions/revolution.extension.parallax.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/extensions/revolution.extension.slideanims.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/revolution/extensions/revolution.extension.video.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/bootstrapValidator.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jplayer/jquery.jplayer.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jplayer/jplayer.playlist.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/jquery.scrollbar.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./resources/js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
